=head1 NAME

Installation instructions


=head2 Download the Sakila database 

Just run F<$DIST/bin/get-db> 

This will download the Sakila database and fix two typos in the
schema: L<http://forums.mysql.com/read.php?121,276811,276811#msg-276811>


=head2 Install Sakila Database

Run F<$DIST/bin/build-db.pl> 

This script will build a configuration file, F<$DIST/bin/local.conf>
which will be used by L</Rose::DB::Object> in the subsequent steps. It
will also print two system commands to STDOUT which you must run to
build the Sakila database.

For some reason, these commands don't work from within a Perl program.

=head2 Point Rose::DB::Object::Loader at the Sakila database

After sourcing the config file, run loader:pl:

  cd $DIST/bin
  . ./config
  ./loader.pl



=head2 Now it's time to play!

  cd $DIST/bin
  ./rdbofaq list_actors

You can call F<rdbofaq> with the name of any .pm file in 
$DIST/lib/MyApp/Command/*


